name: change_app_package_name
description: Change App Package Name with single command. Update AndroidManifest, build.gradle, MainActivity files & move MainActivity file to new directory structure automatically.
version: 0.1.3
maintainer: Atiq Samtia (@AtiqSamtia)
homepage: https://github.com/atiqsamtia/change_app_package_name

environment:
  sdk: ">=2.1.0 <3.0.0"
